import { StyleSheet } from "react-native";
import { StdColor } from "../../components/style/StdStyle";

export const styles = StyleSheet.create({
  containerClients: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItens: "center",
    height: 60,
    marginTop: 12,
  },
  titleScreen: {
    color: StdColor.white[80],
    fontSize: 42,
    width: "100%",
    textAlign: "center",
    marginBottom: 12,
  },
  iconPlusClient: {
    color: StdColor.secndaryColor[40],
    fontSize: 28,
    position: "absolute",
    right: 0,
    top: 8,
    width: 50,
    height: 50,
  },
  containerDescriptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 50,
    borderBottomColor: StdColor.white[80],
    borderBottomWidth: 1,
  },
  descriptionsText: {
    height: 30,
    color: StdColor.white[80],
    fontSize: 24,
    width: "30%",
  },
  clientItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 50,
    backgroundColor: StdColor.white[20],
    marginTop: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  clientInfo: {
    color: StdColor.black[80],
    fontSize: 22,
    fontWeight: "bold",
    justifyContent: "space-between",
  },
  clientContainerDebt: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "50%",
    height: 50,
    paddingLeft: 32,
  },
  inputName: {
    height: 50,
    width: "100%",
    backgroundColor: StdColor.white[20],
    borderRadius: 16,
    paddingLeft: 16,
    marginTop: 12,
    color: StdColor.black[80],
    fontSize: 22,
    fontWeight: "bold",
  },
  buttonAddClient: {
    backgroundColor: StdColor.secndaryColor[40],
    width: "100%",
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  buttonCancel: {
    backgroundColor: StdColor.black[20],
    width: "100%",
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  buttonAddText: {
    color: StdColor.black[80],
    fontSize: 22,
    fontWeight: "bold",
  },
  buttonCancelText: {
    color: StdColor.white[80],
    fontSize: 22,
    fontWeight: "bold",
  },
});
